export const env = {
  SALESFORCE_API_URL: process.env.SALESFORCE_API_URL ?? "",
  SALESFORCE_AUTH_URL: process.env.SALESFORCE_AUTH_URL ?? "",
  SALESFORCE_CLIENT_ID: process.env.SALESFORCE_CLIENT_ID ?? "",
  SALESFORCE_CLIENT_SECRET: process.env.SALESFORCE_CLIENT_SECRET ?? "",
  SALESFORCE_USERNAME: process.env.SALESFORCE_USERNAME ?? "",
  SALESFORCE_PASSWORD: process.env.SALESFORCE_PASSWORD ?? "",
  NEXT_PUBLIC_RECAPTCHA_SITE_KEY: process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY ?? "",
  PROXY_URL: process.env.PROXY_URL || '',
  USE_PROXY: process.env.USE_PROXY || true,
};
